version: "3.1"
services:
 db:
  container_name: drones-sql
  image: mysql
  command: --default-authentication-plugin=mysql_native_password --default-time-zone='UTC'
  restart: always
  environment:
   MYSQL_DATABASE: "drones_db"
   MYSQL_ROOT_PASSWORD: "example"
  ports:
   - "3306:3306"
  volumes:
   - ./db:/var/lib/mysql
   - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
