apiVersion: apps/v1
kind: Deployment
metadata:
 name: drones-monitor-depl
spec:
 replicas: 1
 selector:
  matchLabels:
   app: drones-monitor
 template:
  metadata:
   labels:
    app: drones-monitor
  spec:
   containers:
    - name: drones-monitor
      image: ghcr.io/ginnyvt/drones-observer:server
      envFrom:
       - secretRef:
          name: backend-env
      resources:
       requests:
        memory: "128Mi"
        cpu: "0.25"
       limits:
        memory: "256Mi"
        cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
 name: drones-monitor-srv
spec:
 selector:
  app: drones-monitor
 ports:
  - name: drones-monitor
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 annotations:
  dev.okteto.com/generate-host: "true"
 name: drones-monitor-ingress
spec:
 rules:
  - http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: drones-monitor-srv
          port:
           number: 8000
