apiVersion: v1
kind: Service
metadata:
 name: mariadb
 labels:
  app: mariadb
spec:
 ports:
  - protocol: TCP
    name: mysql
    port: 3306
    targetPort: 3306
 clusterIP: None
 selector:
  app: mariadb
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: initsql
data:
 db-init.sql: |
  USE drones_db;

  CREATE TABLE IF NOT EXISTS `violated_drone` (
  snapped_at DATETIME NOT NULL,
  drone_serial_no VARCHAR(50) NOT NULL,
  drone_positionX NUMERIC(20,12) NOT NULL,
  drone_positionY NUMERIC(20,12) NOT NULL,
  distance_to_nest NUMERIC(20,12) NOT NULL,
  pilot_firstName VARCHAR(50) NOT NULL, 
  pilot_lastName VARCHAR(50) NOT NULL,
  pilot_phone VARCHAR(50),
  pilot_email VARCHAR(50),
  PRIMARY KEY (snapped_at, drone_serial_no)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mariadb
spec:
 serviceName: "mariadb"
 replicas: 1
 selector:
  matchLabels:
   app: mariadb
 template:
  metadata:
   labels:
    app: mariadb
  spec:
   securityContext:
    fsGroup: 999
    runAsUser: 999
    runAsGroup: 999
    runAsNonRoot: true
   containers:
    - name: mariadb
      image: mariadb:10.9
      imagePullPolicy: Always
      ports:
       - containerPort: 3306
         protocol: TCP
         name: mariadb
      env:
       - name: MARIADB_AUTO_UPGRADE
         value: "true"
       - name: MARIADB_RANDOM_ROOT_PASSWORD
         value: "true"
       - name: MARIADB_DATABASE
         valueFrom:
          secretKeyRef:
           name: db-env
           key: DATABASE_NAME
       - name: MARIADB_USER
         valueFrom:
          secretKeyRef:
           name: db-env
           key: DATABASE_USER
       - name: MARIADB_PASSWORD
         valueFrom:
          secretKeyRef:
           name: db-env
           key: DATABASE_PASS
      volumeMounts:
       - name: data
         mountPath: /var/lib/mysql
       - name: initsql
         mountPath: /docker-entrypoint-initdb.d/db-init.sql
         subPath: db-init.sql
   volumes:
    - name: initsql
      configMap:
       name: initsql

 volumeClaimTemplates:
  - metadata:
     name: data
    spec:
     accessModes: ["ReadWriteOnce"]
     resources:
      requests:
       storage: 2Gi
